### ISSUE TITLE
CfP prominenter verlinken

### ISSUE THREAD

**Issue by dboehmer** [FrankfurtPM/GPW-Checklists#14]
Der CfP ist aktuell nur über die News zu finden, die schon nicht mehr die neuste ist und deshalb quasi im Archiv verschwunden ist. Der CfP sollte meiner Meinung nach mindestens so prominent platziert werden wie aktuell der CoC, wenigstens solange Vorträge eingereicht werden können/sollen.

**Comment by reneeb** [comment]
Bitte mal auf der Startseite schauen... CfP taucht jetzt oben in der Navi auf und es gibt einen extra Bereich.

Meldungen das Act! betreffend bitte unter https://github.com/Act-Conferences/gpw2022 einreichen.
