### ISSUE TITLE
Sketchnote Hands-on

### ISSUE THREAD

**Issue by reneeb** [FrankfurtPM/GPW-Checklists#2]
Etwas völlig losgelöst von Programmierung: Sketchnotes sind klasse zum schnellen Skizzieren von Vorträgen. Wolfgang K. hat angeboten einen solchen Hands-on-Workshop zu machen...

**Comment by rehsack** [comment]
👍

**Comment by wki** [comment]
Über die Dauer einer solchen Session muss man sich noch unterhalten. Ich denke ein halbtägiges Hands-On Training mit vorheriger Anmeldung der Teilnehmer und einem Unkostenbeitrag für das "Material" wäre vermutlich für die meisten akzeptabel.

**Comment by frankfurt-pm** [comment]
Ahoi,

gerade heute ist mein Sketchnote-Workshop-Buch angekommen.
Könnt ihr Gedanken lesen oder sind wir alle Meme-Opfer?


Am 12.04.2018 um 08:44 schrieb Renee:
>
> Etwas völlig losgelöst von Programmierung: Sketchnotes sind klasse zum 
> schnellen Skizzieren von Vorträgen. Wolfgang K. hat angeboten einen 
> solchen Hands-on-Workshop zu machen...
>

++

Sören

-- 
Sören Laird Sörries
(069) 34877638

**Comment by reneeb** [comment]
Danke @wki für die Durchführung des Sketchnote-Workshops...
