### ISSUE TITLE
HowTo für Aufnahmen

### ISSUE THREAD

**Issue by reneeb** [FrankfurtPM/GPW-Checklists#8]
Die Vorträge des GPW 2021 werden **vor** dem Workshop durch die Vortragenden aufgenommen. Dafür muss ein [HowTo](/FrankfurtPM/GPW-Checklists/wiki/SpeakerHowToRecording) geschrieben werden.

**Comment by Corion** [comment]
Aktueller Stand

https://github.com/FrankfurtPM/GPW-Checklists/wiki/Aufnahmen-mit-OBS---Recording-with-OBS
