### ISSUE TITLE
Fragen-Bot schreiben

### ISSUE THREAD

**Issue by reneeb** [FrankfurtPM/GPW-Checklists#9]
Der Bot muss die Fragen im Chat zu einem Vortrag erkennen und in ein Etherpad  speichern. Siehe auch [Wiki](/FrankfurtPM/GPW-Checklists/wiki/OnlineWorkshop2021).

**Comment by moseschmiedel** [comment]
Ich hab da gestern schonmal nen Prototypen gebaut: https://github.com/moseschmiedel/question-bot.
Momentan benutzt der noch eine Hardgecodede Etherpadinstanz, ich würde mich die Tage aber mal um Rekonfigurierbarkeit kümmern.

**Comment by moseschmiedel** [comment]
So mit `7eca3240ad3fdd192ded9f3cbe4d02042274b535` sollte mein Bot jetzt auch rekonfigurierbar sein.
Hier ist mal ein Beispiel Etherpad, in das der Bot geschrieben hat:
![Screenshot_2021-01-21_16-16-24](https://user-images.githubusercontent.com/58808540/105370682-1bbe1a00-5c04-11eb-89bd-2bfd2868c80d.png)

**Comment by reneeb** [comment]
Danke für den Bot. Sieht gut aus.
